### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by FeiiYin** [Samir55/SATR#1]
Hi, thanks for your awesome work.
I would like to ask how to test on my custom data, like point cloud, mesh or nerf obtained from my training.
Can you provide several scripts or some insight?
Thanks in advance.

**Comment by Samir55** [comment]
Hi @FeiiYin, I appreciate your interest. Our code takes as input a 3D mesh. Please look at the demo section in the readme file [here](https://github.com/Samir55/SATR#demo), which takes a config file. A single command operates only on one mesh, so you should create a separate command for each mesh.
